#!/usr/bin/perl -w

#
# Example of use of the NVA-API library
#
# example takes one paramater - a path of the element
# and prints out its value and some other information
#
# in this example exceptions are not handled 
# explicitely, once any nva-api function
# rises an exception, the excecution is stopped
# and the stack trace printed out
#
# Piotr Poznanski <Piotr.Poznanski@cern.ch>
#

# EDG prologue

BEGIN {
  $ENV{"EDG_LOCATION"} ||= "/opt/edg";
  $ENV{"EDG_LOCATION_VAR"} ||= $ENV{"EDG_LOCATION"}."/var";
  unshift (@INC, $ENV{"EDG_LOCATION"}."/lib/perl");
}

use strict;
use EDG::WP4::CCM::CacheManager;

my $cp = $ARGV[0];

unless ($cp) {
  die ("usage: $0 element-path\n");
}

# empty credentails
my $cred = 0;

# create new CacheManager (default cache will be used)
my $cm = EDG::WP4::CCM::CacheManager->new(); 

# get (locked) current configuration
my $cfg = $cm->getLockedConfiguration($cred);

my $el = $cfg->getElement($cp);


if ($el->isResource()) {print "Resource:   ";}
elsif ($el->isProperty()) {print "Property:   ";}
else {die ("element is neither resource nor property");}

print $el->getName()."\n";
print "Path:       ".$el->getPath()->toString()."\n";
print "Derivation: ".$el->getDerivation()."\n";
print "Checksum:   ".$el->getChecksum()."\n";
print "Value:      ".$el->getValue()."\n";
