#!/usr/bin/perl -w




use Test::Harness;



my @test_files=qw(test-ccfg.pl test-path.pl test-property.pl test-syncfile.pl
                  test-element.pl test-resource.pl);

# not working tests yet

#push(@test_files,qw(test-configuration.pl test-cachemanager.pl));

runtests(@test_files);



